name: HappyGhastSpeed
version: 1.1.0
main: com.graytr.happyghast.HappyGhastSpeedPlugin
api-version: '1.21'
description: Make Speed I/II potions boost Happy Ghasts' flight speed
author: Graytr & ChatGPT
